# Generated by Django 5.2.18 on 2026-10-08 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='beat',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Optional short/tagged preview that visitors can stream before buying.', null=True, upload_to='previews/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(help_text='Full-quality file. Only delivered to buyers after payment.', upload_to='beats/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'aiff', 'aif', 'flac', 'm4a', 'zip'])]),
        ),
    ]
