# Generated by Django 5.2.18 on 2026-10-09 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "General question"),
                            ("custom", "Custom beat or session"),
                            ("licensing", "Licensing"),
                            ("support", "Payment or download help"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(max_length=3000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_handled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
