# Generated by Django 5.2.18 on 2026-10-09 00:41

import catalog.storage
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=60)),
                (
                    "bpm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("musical_key", models.CharField(blank=True, help_text="For example: C# minor", max_length=20)),
                (
                    "price_ghs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Ghana cedis (GHS).",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="covers/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "webp"])],
                    ),
                ),
                (
                    "preview_audio",
                    models.FileField(
                        help_text="Public MP3 preview that visitors can play.",
                        upload_to="previews/",
                        validators=[django.core.validators.FileExtensionValidator(["mp3"])],
                    ),
                ),
                (
                    "full_audio",
                    models.FileField(
                        help_text="Full-quality file. Only buyers can download it. Stored privately.",
                        storage=catalog.storage.PrivateFileStorage(),
                        upload_to="full/",
                        validators=[django.core.validators.FileExtensionValidator(["wav", "mp3", "flac", "zip"])],
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, help_text="Paste a YouTube link. Leave empty if you upload a file instead."
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a video file. Leave empty if you use a YouTube link.",
                        upload_to="videos/",
                        validators=[django.core.validators.FileExtensionValidator(["mp4", "webm", "mov"])],
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="thumbnails/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "webp"])],
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
