# Generated by Django 5.2.18 on 2026-10-09 00:41

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(default=orders.models.new_reference, max_length=64, unique=True)),
                ("amount_ghs", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Awaiting payment"), ("paid", "Paid"), ("failed", "Payment failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=20)),
                (
                    "channel",
                    models.CharField(
                        blank=True, help_text="How the buyer paid, for example mobile_money or bank.", max_length=30
                    ),
                ),
                ("provider_transaction_id", models.CharField(blank=True, max_length=64)),
                ("download_token", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="catalog.beat"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
